// app/layout.tsx
import './globals.css';
import React from 'react';
import NavbarTop from './NavbarTop';
import NavbarBottom from './NavbarBottom';

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by create-next-app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <NavbarTop />
        <main>{children}</main>
        <NavbarBottom />
      </body>
    </html>
  );
}
