// app/layout.tsx
import "./globals.css";
import { ReactNode } from "react";
import { NavbarTop } from "../components/NavbarTop/NavbarTop";
import { NavbarBottom } from "../components/NavbarBottom/NavbarBottom";

export const metadata = {
  title: "My Next.js App",
  description: "Generated by create-next-app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <NavbarTop />
        <main>{children}</main>
        <NavbarBottom />
      </body>
    </html>
  );
}
