// app/layout.tsx
import './globals.css';
import React from 'react';
import TopNavbar from './components/TopNavbar';
import BottomNavbar from './components/BottomNavbar';

export const metadata = {
  title: 'My Next.js App',
  description: 'Generated by create-next-app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <TopNavbar />
        <main>{children}</main>
        <BottomNavbar />
      </body>
    </html>
  );
}
